name: Build dev
on:
  push:
    branches:
      - master
jobs:
  build_dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Build
        uses: flipperdevices/flipperzero-ufbt-action@v0.1.3
        with:
          channel: dev
